name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get install make
        make install
    
    - name: Run the application
      run: |
        make run &
        sleep 20  # Increase sleep time to give server more time to start
        curl -f http://localhost:3000 || exit 1  # Test if the server is running
    
    - name: Check running processes
      run: ps aux
    
    - name: Check open ports
      run: netstat -tuln
